# GuardOverseer by mydeblob. Welcome to the config :)

# ----------------------Class!--------------------------------

# You MUST follow the template below; Give the player the permission guardoverseer.duty
# and the permission of the kit you want him to use
# IMPORTANT** A single player can not have more than one kit permission
# IMPORTANT** You must use item ids, google them if you don't know them
# IMPORTANT** You MUST use the format seen below otherwise the plugin WILL break!
# IMPORTANT** When declaring a name or lore you MUST use _ as a space
# if you dont the plugin will break!
# %n% will create a new line **THIS ONLY WORKS ON THE LORE**
# Set the name or lore to null if you dont want it to appear
# All potions last until the player goes off duty
kits:
   default:
      permission: guardoverseer.default
      kit-items:
        - 302 1 name:&4Guard_Armor lore:&3You_are_on_duty%n%&2Go_protect_some_players! protection:50 unbreaking:50
        - 303 1 name:&4Guard_Armor lore:&3You_are_on_duty%n%&2Go_protect_some_players! protection:50 unbreaking:50
        - 304 1 name:&4Guard_Armor lore:&3You_are_on_duty%n%&2Go_protect_some_players! protection:50 unbreaking:50
        - 305 1 name:&4Guard_Armor lore:&3You_are_on_duty%n%&2Go_protect_some_players! protection:50 unbreaking:50
        - 276 1 name:null lore:null sharpness:20 fireaspect:10
        - 364 32
        - 322:1 2
      potions:
        - speed 2
# ------------------------------------------------------------
# ----------------Misc(Economy, items etc.)------------------
# ------------------------------------------------------------

# This is wether or not to drop guard items when he dies. This will only affect a player
# when they are on /duty
# TRUE will drop items, FALSE won't drop items
drop-items-on-death : false

# This is wether or not a guard should have hunger loss while on duty
# TRUE will have hunger loss, FALSE won't
hunger: true

# These are commands that the player won't be able to perform when he is on duty
disabled-commands:
   - /auc
   - /sell

# This is wether guards who are on duty should be able to hurt each other
# TRUE if they can hurt each other, FALSE if they can't
guard-pvp: false

# This will tell guards who are on duty who hit them and with what. 
# ie: Someones on duty and I hit them with a diamond sword it will say,
# "mydeblob has hit you with a diamond sword!"
# TRUE will tell guards, FALSE won't tell guards
pvp-notifications: true

# This will alert staff if there is a new update available, and if there is download it
# If this is TRUE it will alert staff, if it's FALSE it will be disabled completely
auto-update: true

# This will be a delay between uses of /duty to prevent abuse
# It is in seconds, set to 0 to disable
command-delay: 5

# This allows the guard to drop, remove, and give away the items that he picks up
# while on duty
# ****THE GUARD STILL CANT DROP THE GUARD ITEMS, JUST ITEMS HE PICKS UP****
allow-drop-items: false

# ******************THIS REQUIRES VAULT AND WILL NOT WORK WITHOUT IT****************
# These are permission a guard will have only when he is ON duty
permissions:
   - essentials.togglejail

# These are permissions that will be removed from the guard while he is on duty
# Ex. Remove sell sign permissions so he doesn't sell his items
remove-onduty-permissions:
   - essentials.signs.sell

# This is the amount of money awarded to a player who kills a guard
# Set to 0 to disable
award: 1000

# If this is enabled a player with the same IP as a guard will not get awarded
# money for killing him
# This is to prevent abuse with guards and alts
log-ip: true

# Wether or not to pay the guards for how long they are on duty
pay-guards: true

# If set to true, the guards wont get payed if they are afk for more then 3 minutes or
# if the guards log off
afk: true

# Amount to pay the guards IF pay-guards is true
# This is an hourly rate
# If a player only goes on duty for 30 minutes, he will only be payed for the time
# he was on duty
# By default, they get payed 10,000 an hour
salary: 10000